### ISSUE TITLE
mac cmdbench

### ISSUE THREAD

**Issue by aerickson** [manzik/cmdbench#3]
Happy to help if there's more interest.

Thanks for working on the project. :) Definitely going to use it on linux.

---

```
➜  ~  pip install cmdbench
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting cmdbench
  Using cached https://files.pythonhosted.org/packages/e5/88/743ce3dde282a14270400d9c70d56dd4ad4759e01214d49b826473500b86/cmdbench-0.1.11.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-ng1Ykz/cmdbench/setup.py'"'"'; __file__='"'"'/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-ng1Ykz/cmdbench/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-ng1Ykz/cmdbench/pip-egg-info
         cwd: /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-ng1Ykz/cmdbench/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-ng1Ykz/cmdbench/setup.py", line 7, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
➜  ~  pip3 install cmdbench
Collecting cmdbench
  Using cached cmdbench-0.1.11.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-0d2i_f7z/cmdbench/setup.py'"'"'; __file__='"'"'/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-0d2i_f7z/cmdbench/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4
         cwd: /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-0d2i_f7z/cmdbench/
    Complete output (16 lines):
    running egg_info
    creating /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info
    writing /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/dependency_links.txt
    writing entry points to /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/entry_points.txt
    writing requirements to /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/requires.txt
    writing top-level names to /private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/top_level.txt
    writing manifest file '/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/SOURCES.txt'
    reading manifest file '/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/SOURCES.txt'
    writing manifest file '/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-pip-egg-info-ksb2h8e4/cmdbench.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tb/xncysjgj76j95vbv0bn408600000gn/T/pip-install-0d2i_f7z/cmdbench/setup.py", line 66, in <module>
        raise Exception('Sorry, cmdbench is supported only on the Linux operating system.\nIf you would like to use cmdbench on macOS, please create an issue at https://github.com/manzik/cmdbench/issues to request the feature.')
    Exception: Sorry, cmdbench is supported only on the Linux operating system.
    If you would like to use cmdbench on macOS, please create an issue at https://github.com/manzik/cmdbench/issues to request the feature.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
➜  ~  

```

**Comment by manzik** [comment]
Thanks for reaching out Andrew!
I added macOS support. I also went ahead and added Windows support too as editing the code for macOS support fixed most of the issues with Windows too.
I haven't done much testing on macOS but verified that it works and the results are correct. 
Just one thing: macOS does not allow process-specific disk usage info to be collected so that info will be unavailable on macOS when you use this package.
Feel free to open another issue if something is off!
Cheers
